/*
################################################################################
# Euler #2
################################################################################
#
# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
#
################################################################################
#
# 4613732
#
*/
package main

import "fmt"


func fibSumEvenTerms(n int) int {

	a, b, sum := 1, 1, 0;

	for (b < n) {
		a, b = b, a + b;
		if (b % 2 == 0) {
			sum += b
		}
	}
	return sum;
}

func main() {

	fmt.Println( fibSumEvenTerms(4000000) );
}